### ISSUE TITLE
Advanced Aggregate Functions

### ISSUE THREAD

**Issue by davegravy** [esnet/pond#105] opened 2018-02-21 20:46 UTC
I'm wanting to apply an advanced downsampling algorithm ([Largest Triangle Three Buckets](https://skemman.is/bitstream/1946/15343/3/SS_MSthesis.pdf#page=43)) to my TimeSeries. As far as I can tell implementing this isn't currently possible because the custom aggregator functions are only passed a list of values in the current window and no data from previous and next windows which seem to be necessary for this algo.

Could this be changed?

I should also mention I'm wanting to use this with react-timeseries-charts, which I gather is pegged to pond v0.8 (for now? forever?)

**Comment by pjm17971** [comment] 2018-02-23 21:06
Yeah, I've seen that thesis before. Implementing something like that would be really fantastic.

In the pre-1.0-alpha Pond versions, this doesn't fit in at all with how aggregation functions work, as you correctly noted. Your best bet would be to implement it directly in timeseries and send me a PR. If it looks good, I'll work out the versioning and get it to work with the charts library. It probably doesn't have to work for streaming data, so you can avoid the processing chain approach. I think it's a matter of taking the events in the timeseries collection, grouping them up into a list of buckets, and then implementing a function that takes the three buckets. I guess the first and last buckets are special in this algorithm in that they contain just one point. If that wasn't the case Pond could do some of the work. You can probably still use the Index code to map the windowing into a grouping and keep the API similar to the fixedWindowRollup one.

For the 1.0+ version, I might be able to work something out. Let me experiment. But that's further down the road.

As for versions in general, there will be a charts version based on pond v1.0 in the future. However, I'm committed to support the older versions of these and will update the pre-1.0 charts and pond as needed.

**Comment by pjm17971** [comment] 2018-02-23 21:39
As a specific detail, I guess this could only work on a single channel timeseries, because the aggregation is a specific representative point. Probably need to give that some thought.

**Comment by davegravy** [comment] 2018-02-25 20:45
Thanks for the insight. The feature is a bit daunting for me as I'm a novice but getting steadily better with time. Hopefully I can soon swing this.

**Comment by davegravy** [comment] 2018-02-25 20:54
Thanks for the insight. I'm a novice and this looks daunting, but I'm steadily improving so hopefully in time I can swing it.

**Comment by pjm17971** [comment] 2018-02-26 16:41
Duplicate of #9 so I'm closing this one

**Closed by pjm17971** 2018-02-26 16:41 UTC
Labels: enhancement
